TRUNCATE TABLE [sec].[BotCodeKeyword];
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('true'   ,  5, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('false'  ,  5, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('eval'   ,  7, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('compile', 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('range'  , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('import' , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('sleep'  , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('\n'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('{'      , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('}'      , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('['      , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES (']'      , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('./'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('../'    , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('.ini'   , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('.reg'   , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('.bat'   , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('.cmd'   , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('.sql'   , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('--'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('++'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES (':='     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('\'      , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('\\'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('/'      ,  3, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('//'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('&'      ,  3, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('&&'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('|'      ,  6, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('||'     , 10, 1);
INSERT INTO [sec].[BotCodeKeyword] ([Keyword], [Weight], [Active]) VALUES ('win.ini', 10, 1);
